# Generated by Django 5.1.2 on 2024-10-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
