# Generated by Django 5.1.2 on 2024-10-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='default_password', max_length=12),
        ),
    ]
